#pragma once
#include <juce_core/juce_core.h>

namespace opensynth {

struct PresetInfo {
    juce::String id;
    juce::String name;
    juce::String category;
};

inline const int kNumPresets = 1424;

inline const PresetInfo kPresets[] = {
    {"pm-guitar-01", "Nylon Guitar PM", "acousticGuitar"},
    {"pm-guitar-02", "Steel String Guitar PM", "acousticGuitar"},
    {"pm-bass-01", "Acoustic Bass PM", "bassGuitar"},
    {"pm-harp-01", "Celtic Harp PM", "ethnic"},
    {"pm-marimba-01", "Marimba PM", "mallets"},
    {"pm-vibes-01", "Vibraphone PM", "mallets"},
    {"pm-steel-01", "Steel Drum PM", "mallets"},
    {"pm-xylo-01", "Xylophone PM", "mallets"},
    {"pm-clav-01", "Clavinet PM", "keys"},
    {"pm-harpsichord-01", "Harpsichord PM", "keys"},
    {"pm-sitar-01", "Sitar PM", "ethnic"},
    {"pm-koto-01", "Koto PM", "ethnic"},
    {"factory-01", "Blade Runner Pad", "pads"},
    {"factory-02", "Stranger Things Pad", "pads"},
    {"factory-03", "Neon Lead", "leads"},
    {"factory-04", "Laser Lead", "leads"},
    {"factory-05", "Sub Bass", "bass"},
    {"factory-06", "Synth Bass", "bass"},
    {"factory-07", "DX7 Bells", "keys"},
    {"factory-08", "Electric Piano", "keys"},
    {"factory-09", "Outrun Arp", "arps"},
    {"factory-10", "Crystal Arp", "arps"},
    {"factory-11", "Sweep Riser", "fx"},
    {"factory-12", "Sci-Fi Zap", "fx"},
    {"factory-13", "Retrowave Pad", "synthwave"},
    {"factory-14", "Sunset Drive", "synthwave"},
    {"factory-15", "Init Patch", "custom"},
    {"factory-16", "Bass Following", "custom"},
    {"factory-17", "Vangelis Strings", "pads"},
    {"factory-18", "Vocal Choir Pad", "pads"},
    {"factory-19", "Glacier Pad", "pads"},
    {"factory-20", "Supersaw Lead", "leads"},
    {"factory-21", "Square Wave Pulse", "leads"},
    {"factory-22", "Acid Lead", "leads"},
    {"factory-23", "Reese Bass", "bass"},
    {"factory-24", "Wobble Bass", "bass"},
    {"factory-25", "Juno Bass", "bass"},
    {"factory-26", "Drum & Bass Sub", "bass"},
    {"factory-27", "FM Bell Tower", "keys"},
    {"factory-28", "Mellow Wurli", "keys"},
    {"factory-29", "Pluck Arp", "arps"},
    {"factory-30", "Marimba Arp", "arps"},
    {"factory-31", "Noise Riser", "fx"},
    {"factory-32", "Impact Hit", "fx"},
    {"factory-33", "Drone Sweep", "fx"},
    {"factory-34", "Miami Lights", "synthwave"},
    {"factory-35", "Outrun Bassline", "synthwave"},
    {"factory-36", "Neon Sunset Lead", "synthwave"},
    {"factory-37", "Gated Reverb Hit", "synthwave"},
    {"factory-38", "Industrial Grime", "bass"},
    {"factory-39", "Bitcrushed Lead", "leads"},
    {"factory-40", "Tube Overdrive Bass", "bass"},
    {"factory-41", "Hard Clipping Lead", "leads"},
    {"factory-42", "Cyberpunk Skyline", "pads"},
    {"factory-43", "Surge Acid", "leads"},
    {"factory-44", "Vital Wavetable", "keys"},
    {"factory-45", "Helms Deep", "bass"},
    {"factory-46", "OB-Xd Brass", "keys"},
    {"factory-47", "Dexed Crystal", "keys"},
    {"factory-48", "Zyn Soft Pad", "pads"},
    {"factory-49", "Yoshimi Dream", "arps"},
    {"factory-50", "Synthsharks Grid", "synthwave"},
    {"factory-51", "Dreamscape", "pads"},
    {"factory-52", "Dark Matter", "pads"},
    {"factory-53", "Heavenly Choir", "pads"},
    {"factory-54", "Analog Strings", "pads"},
    {"factory-55", "Tundra Wind", "pads"},
    {"factory-56", "Warm Organ", "pads"},
    {"factory-57", "Dawn Chorus", "pads"},
    {"factory-58", "Shimmer Bells", "pads"},
    {"factory-59", "Moog Voyager", "leads"},
    {"factory-60", "Euro Trance", "leads"},
    {"factory-61", "808 Square", "leads"},
    {"factory-62", "Expressive Filter", "leads"},
    {"factory-63", "Calliope", "leads"},
    {"factory-64", "Distorted Solo", "leads"},
    {"factory-65", "Fuzzy Octave", "leads"},
    {"factory-66", "Hardstyle Saw", "leads"},
    {"factory-67", "Electro Funk", "bass"},
    {"factory-68", "808 Deep", "bass"},
    {"factory-69", "Growl Dubstep", "bass"},
    {"factory-70", "Rubber Pluck", "bass"},
    {"factory-71", "FM Bass", "bass"},
    {"factory-72", "PWM Bass", "bass"},
    {"factory-73", "Lo-Fi Bass", "bass"},
    {"factory-74", "Neuro Reese", "bass"},
    {"factory-75", "Bright Organ", "keys"},
    {"factory-76", "Funk Clavinet", "keys"},
    {"factory-77", "Harpsichord", "keys"},
    {"factory-78", "Glass Marimba", "keys"},
    {"factory-79", "Music Box", "keys"},
    {"factory-80", "Toy Piano", "keys"},
    {"factory-81", "Bubbles", "arps"},
    {"factory-82", "Pulsar", "arps"},
    {"factory-83", "Trance Gate", "arps"},
    {"factory-84", "Fractal", "arps"},
    {"factory-85", "Rising Sun", "arps"},
    {"factory-86", "Spooky Arp", "arps"},
    {"factory-87", "Laser Beam", "fx"},
    {"factory-88", "Space Glide", "fx"},
    {"factory-89", "Explosion", "fx"},
    {"factory-90", "Alien Talk", "fx"},
    {"factory-91", "Sub Drop", "fx"},
    {"factory-92", "Glitch Hit", "fx"},
    {"factory-93", "Chase Sequence", "synthwave"},
    {"factory-94", "Vaporwave", "synthwave"},
    {"factory-95", "A E S T H E T I C", "synthwave"},
    {"factory-96", "Night Rider", "synthwave"},
    {"factory-97", "Darksynth Lead", "synthwave"},
    {"factory-98", "Retrowave Bassline", "synthwave"},
    {"factory-99", "Weather Report", "custom"},
    {"factory-100", "Rain Dance", "custom"},
    {"factory-101", "Morning Light", "custom"},
    {"factory-102", "Deep Space", "custom"},
    {"factory-103", "Nebula Haze", "pads"},
    {"factory-104", "Solar Wind", "pads"},
    {"factory-105", "Enchanted Forest", "pads"},
    {"factory-106", "Digital Aurora", "pads"},
    {"factory-107", "Underwater Cathedral", "pads"},
    {"factory-108", "Crimson Horizon", "pads"},
    {"factory-109", "Lunar Surface", "pads"},
    {"factory-110", "Hologram Dream", "pads"},
    {"factory-111", "Velvet Dusk", "pads"},
    {"factory-112", "Ionosphere", "pads"},
    {"factory-113", "Misty Moor", "pads"},
    {"factory-114", "Crystalium", "pads"},
    {"factory-115", "Abyssal Plain", "pads"},
    {"factory-116", "Stratosphere", "pads"},
    {"factory-117", "Phantom Organ", "pads"},
    {"factory-118", "Arctic Glow", "pads"},
    {"factory-119", "Wistful Waves", "pads"},
    {"factory-120", "Temple Bells Pad", "pads"},
    {"factory-121", "Neon Rain", "pads"},
    {"factory-122", "Pastel Sky", "pads"},
    {"factory-123", "Dark Star Pad", "pads"},
    {"factory-124", "Morning Dew", "pads"},
    {"factory-125", "Spectral Haze", "pads"},
    {"factory-126", "Golden Hour", "pads"},
    {"factory-127", "Ocean Floor", "pads"},
    {"factory-128", "Starfield", "pads"},
    {"factory-129", "Silk Cloud", "pads"},
    {"factory-130", "Cathedral Choir", "pads"},
    {"factory-131", "Polar Night", "pads"},
    {"factory-132", "Celestial Drift", "pads"},
    {"factory-133", "Amber Field", "pads"},
    {"factory-134", "Astral Plane", "pads"},
    {"factory-135", "Aurora Borealis", "pads"},
    {"factory-136", "Mirage", "pads"},
    {"factory-137", "Ethereal Voice", "pads"},
    {"factory-138", "Fusion Lead", "leads"},
    {"factory-139", "Razor Lead", "leads"},
    {"factory-140", "Warm Flute Lead", "leads"},
    {"factory-141", "Grungy Saw", "leads"},
    {"factory-142", "Digital Scream", "leads"},
    {"factory-143", "Pentaphonic", "leads"},
    {"factory-144", "Resonant Lead", "leads"},
    {"factory-145", "Dual Square Lead", "leads"},
    {"factory-146", "Velocity Lead", "leads"},
    {"factory-147", "Hoover Lead", "leads"},
    {"factory-148", "Sync Lead", "leads"},
    {"factory-149", "Chiff Lead", "leads"},
    {"factory-150", "Overdriven Organ", "leads"},
    {"factory-151", "Glass Lead", "leads"},
    {"factory-152", "Pulse Width Lead", "leads"},
    {"factory-153", "Wah Lead", "leads"},
    {"factory-154", "Detuned Unison", "leads"},
    {"factory-155", "Harmonic Lead", "leads"},
    {"factory-156", "Nasty Lead", "leads"},
    {"factory-157", "Feedback Lead", "leads"},
    {"factory-158", "Plastic Horn", "leads"},
    {"factory-159", "Metal Lead", "leads"},
    {"factory-160", "Whistle Tone", "leads"},
    {"factory-161", "Funky Lead", "leads"},
    {"factory-162", "Tropical Lead", "leads"},
    {"factory-163", "Hard Lead", "leads"},
    {"factory-164", "Soft Pad Lead", "leads"},
    {"factory-165", "Octave Lead", "leads"},
    {"factory-166", "Sitar Lead", "leads"},
    {"factory-167", "Reverb Drenched", "leads"},
    {"factory-168", "Atari Lead", "leads"},
    {"factory-169", "Power Synth", "leads"},
    {"factory-170", "Acid Melt", "leads"},
    {"factory-171", "Space Lead", "leads"},
    {"factory-172", "Reso Stack", "leads"},
    {"factory-173", "Future Bass", "bass"},
    {"factory-174", "808 Sub Boom", "bass"},
    {"factory-175", "Square Bass", "bass"},
    {"factory-176", "Slap Bass", "bass"},
    {"factory-177", "Filtered Acid", "bass"},
    {"factory-178", "Submarine", "bass"},
    {"factory-179", "Gritty Reese", "bass"},
    {"factory-180", "Tape Bass", "bass"},
    {"factory-181", "808 Slide", "bass"},
    {"factory-182", "Electric Bass", "bass"},
    {"factory-183", "Wobble Dub", "bass"},
    {"factory-184", "Moog Bass", "bass"},
    {"factory-185", "Rumble Bass", "bass"},
    {"factory-186", "Minimal Bass", "bass"},
    {"factory-187", "Club Kick Bass", "bass"},
    {"factory-188", "Sine Sub Layer", "bass"},
    {"factory-189", "DnB Reece", "bass"},
    {"factory-190", "Fingered Bass", "bass"},
    {"factory-191", "Acid 303", "bass"},
    {"factory-192", "Boogie Bass", "bass"},
    {"factory-193", "Distorted Sub", "bass"},
    {"factory-194", "Triangle Sub", "bass"},
    {"factory-195", "Perc Bass", "bass"},
    {"factory-196", "Warehouse Bass", "bass"},
    {"factory-197", "Bubble Bass", "bass"},
    {"factory-198", "Jazz Walk Bass", "bass"},
    {"factory-199", "Trance Bassline", "bass"},
    {"factory-200", "Rubber Band Bass", "bass"},
    {"factory-201", "Deep House Bass", "bass"},
    {"factory-202", "Clank Bass", "bass"},
    {"factory-203", "Vibraphone", "keys"},
    {"factory-204", "Tine EP", "keys"},
    {"factory-205", "Steel Drums", "keys"},
    {"factory-206", "Clavinet Wah", "keys"},
    {"factory-207", "Glockenspiel", "keys"},
    {"factory-208", "Reed Organ", "keys"},
    {"factory-209", "Celesta", "keys"},
    {"factory-210", "Synth Clav", "keys"},
    {"factory-211", "Balafon", "keys"},
    {"factory-212", "Doo-Wop Organ", "keys"},
    {"factory-213", "Kalimba", "keys"},
    {"factory-214", "Pipe Organ", "keys"},
    {"factory-215", "Dream Bells", "keys"},
    {"factory-216", "FM Keys", "keys"},
    {"factory-217", "Tremolo Organ", "keys"},
    {"factory-218", "Mallets", "keys"},
    {"factory-219", "Wurlitzer EP", "keys"},
    {"factory-220", "Marimba Bright", "keys"},
    {"factory-221", "Farfisa Organ", "keys"},
    {"factory-222", "Bell Pad", "keys"},
    {"factory-223", "Honky Tonk", "keys"},
    {"factory-224", "Tubular Bells", "keys"},
    {"factory-225", "Electric Grand", "keys"},
    {"factory-226", "Toy Xylophone", "keys"},
    {"factory-227", "Mellow Rhodes", "keys"},
    {"factory-228", "Noodle Arp", "arps"},
    {"factory-229", "Wasp Arp", "arps"},
    {"factory-230", "Glass Arp", "arps"},
    {"factory-231", "Saw Stab", "arps"},
    {"factory-232", "Ghost Arp", "arps"},
    {"factory-233", "Fizz Arp", "arps"},
    {"factory-234", "Sine Arp", "arps"},
    {"factory-235", "Tech Arp", "arps"},
    {"factory-236", "Warm Arp", "arps"},
    {"factory-237", "Rave Stab", "arps"},
    {"factory-238", "Ping Pong Arp", "arps"},
    {"factory-239", "Chiptune Arp", "arps"},
    {"factory-240", "Pulse Arp", "arps"},
    {"factory-241", "Drip Arp", "arps"},
    {"factory-242", "Reso Arp", "arps"},
    {"factory-243", "Flute Arp", "arps"},
    {"factory-244", "Grit Arp", "arps"},
    {"factory-245", "Dream Arp", "arps"},
    {"factory-246", "Analog Arp", "arps"},
    {"factory-247", "Bubble Arp", "arps"},
    {"factory-248", "Staccato Arp", "arps"},
    {"factory-249", "Space Arp", "arps"},
    {"factory-250", "Pluck  Strings", "arps"},
    {"factory-251", "Filtered Arp", "arps"},
    {"factory-252", "Digital Arp", "arps"},
    {"factory-253", "Wind Blow", "fx"},
    {"factory-254", "Frequency Sweep", "fx"},
    {"factory-255", "Laser Blast", "fx"},
    {"factory-256", "Thunder Clap", "fx"},
    {"factory-257", "Siren", "fx"},
    {"factory-258", "Teleport", "fx"},
    {"factory-259", "Spacecraft", "fx"},
    {"factory-260", "Rising Chord", "fx"},
    {"factory-261", "Bass Drop", "fx"},
    {"factory-262", "Metallic Hit", "fx"},
    {"factory-263", "Ominous Hum", "fx"},
    {"factory-264", "Glitch FX", "fx"},
    {"factory-265", "Reverb Swell", "fx"},
    {"factory-266", "Alien Signal", "fx"},
    {"factory-267", "Power Up", "fx"},
    {"factory-268", "Heartbeat", "fx"},
    {"factory-269", "White Noise Sweep", "fx"},
    {"factory-270", "Quake Rumble", "fx"},
    {"factory-271", "Phaser Sweep", "fx"},
    {"factory-272", "Robot Voice", "fx"},
    {"factory-273", "Grand Piano", "piano"},
    {"factory-274", "Bright Piano", "piano"},
    {"factory-275", "Honky Tonk Piano", "piano"},
    {"factory-276", "Soft Piano Pad", "piano"},
    {"factory-277", "Electric Piano Classic", "piano"},
    {"factory-279", "FM Piano", "piano"},
    {"factory-280", "Cinematic Piano", "piano"},
    {"factory-281", "Mellow Piano", "piano"},
    {"factory-283", "Piano Strings Layer", "piano"},
    {"factory-284", "Lo-Fi Piano", "piano"},
    {"factory-285", "Rock Piano", "piano"},
    {"factory-286", "Ambient Piano Wash", "piano"},
    {"factory-287", "Jazz Piano", "piano"},
    {"factory-288", "Hammond B3", "organ"},
    {"factory-289", "Jazz Organ", "organ"},
    {"factory-291", "Rock Organ", "organ"},
    {"factory-292", "Cathedral Organ", "organ"},
    {"factory-293", "Farfisa Combo", "organ"},
    {"factory-294", "Vox Continental", "organ"},
    {"factory-295", "Gospel Organ", "organ"},
    {"factory-296", "Percussive Organ", "organ"},
    {"factory-297", "Drawbar Organ", "organ"},
    {"factory-298", "Phaser Organ", "organ"},
    {"factory-299", "Dark Organ", "organ"},
    {"factory-300", "Funky Organ", "organ"},
    {"factory-301", "Organ Bass", "organ"},
    {"factory-302", "Reggae Bubble Organ", "organ"},
    {"factory-303", "Clean Guitar", "guitar"},
    {"factory-304", "Nylon Guitar", "guitar"},
    {"factory-305", "Overdrive Guitar", "guitar"},
    {"factory-306", "Distortion Guitar", "guitar"},
    {"factory-307", "Funk Guitar", "guitar"},
    {"factory-308", "Lead Guitar", "guitar"},
    {"factory-309", "Jazz Guitar", "guitar"},
    {"factory-310", "Twang Guitar", "guitar"},
    {"factory-311", "Ambient Guitar", "guitar"},
    {"factory-312", "Acoustic Strum", "guitar"},
    {"factory-313", "Surf Guitar", "guitar"},
    {"factory-314", "Power Chord", "guitar"},
    {"factory-315", "Twelve String Guitar", "guitar"},
    {"factory-316", "Slide Guitar", "guitar"},
    {"factory-317", "Guitar Harmonics", "guitar"},
    {"factory-318", "String Ensemble", "strings"},
    {"factory-319", "Violin Solo", "strings"},
    {"factory-320", "Cello", "strings"},
    {"factory-321", "Pizzicato Strings", "strings"},
    {"factory-322", "Tremolo Strings", "strings"},
    {"factory-323", "Synth Strings", "strings"},
    {"factory-324", "Warm Strings", "strings"},
    {"factory-325", "Spiccato Strings", "strings"},
    {"factory-326", "Octave Strings", "strings"},
    {"factory-327", "Soft Strings", "strings"},
    {"factory-328", "String Stab", "strings"},
    {"factory-329", "Film Score Strings", "strings"},
    {"factory-330", "Sci-Fi Strings", "strings"},
    {"factory-331", "Staccato Strings", "strings"},
    {"factory-332", "Baroque Strings", "strings"},
    {"factory-333", "Trumpet Solo", "brass"},
    {"factory-334", "Brass Section", "brass"},
    {"factory-335", "Trombone", "brass"},
    {"factory-336", "French Horn", "brass"},
    {"factory-337", "Synth Brass", "brass"},
    {"factory-338", "Saxophone", "brass"},
    {"factory-339", "Brass Stab", "brass"},
    {"factory-340", "Fat Brass", "brass"},
    {"factory-341", "Muted Trumpet", "brass"},
    {"factory-342", "Pop Brass", "brass"},
    {"factory-343", "Tuba", "brass"},
    {"factory-344", "Fanfare Brass", "brass"},
    {"factory-345", "Soft Brass Pad", "brass"},
    {"factory-346", "Flugelhorn", "brass"},
    {"factory-347", "Brass Orchestra", "brass"},
    {"factory-349", "Warm Choir Pad", "choir"},
    {"factory-350", "Angelic Voices", "choir"},
    {"factory-351", "Male Chorus", "choir"},
    {"factory-352", "Synth Choir", "choir"},
    {"factory-353", "Operatic Soprano", "choir"},
    {"factory-354", "Distant Choir", "choir"},
    {"factory-355", "Gospel Choir", "choir"},
    {"factory-356", "Ethereal Voices", "choir"},
    {"factory-357", "Choir Stab", "choir"},
    {"factory-358", "Dark Choir", "choir"},
    {"factory-359", "Children Choir", "choir"},
    {"factory-360", "Vocoder Choir", "choir"},
    {"factory-361", "Haunting Voices", "choir"},
    {"factory-362", "Celestial Choir", "choir"},
    {"factory-364", "Marimba", "percussion"},
    {"factory-365", "Xylophone", "percussion"},
    {"factory-370", "Timpani", "percussion"},
    {"factory-371", "Pluck Synth", "percussion"},
    {"factory-373", "808 Cowbell", "percussion"},
    {"factory-374", "Crystal Mallet", "percussion"},
    {"factory-375", "Log Drum", "percussion"},
    {"factory-376", "FM Percussion", "percussion"},
    {"factory-377", "Wind Chimes", "percussion"},
    {"factory-378", "Amen Chop Bass", "bass"},
    {"factory-379", "Neuro Stab", "leads"},
    {"factory-380", "Liquid Funk Bass", "bass"},
    {"factory-381", "Jump Up Reese", "bass"},
    {"factory-382", "Half Time Growl", "bass"},
    {"factory-383", "Roller Pad", "pads"},
    {"factory-384", "Atmospheric Break", "arps"},
    {"factory-385", "Tech Stepper", "leads"},
    {"factory-386", "Minimal Drum Bass", "bass"},
    {"factory-387", "Jungle Reese", "bass"},
    {"factory-388", "Epic Brass Stab", "leads"},
    {"factory-389", "Orchestral Swell", "pads"},
    {"factory-390", "Tension String", "pads"},
    {"factory-391", "Battle Drums", "fx"},
    {"factory-392", "Sci-Fi Alarm", "fx"},
    {"factory-393", "Heartbeat Sub", "bass"},
    {"factory-395", "War Horn", "fx"},
    {"factory-396", "Ghost Whispers", "pads"},
    {"factory-397", "Victory Fanfare", "leads"},
    {"factory-398", "Deep Drone", "pads"},
    {"factory-399", "Granular Mist", "pads"},
    {"factory-400", "Binaural Beats", "pads"},
    {"factory-401", "Rain Field", "pads"},
    {"factory-402", "Solar Drone", "pads"},
    {"factory-403", "Lost Signal", "fx"},
    {"factory-404", "Ice Cave", "pads"},
    {"factory-405", "Zen Garden", "pads"},
    {"factory-406", "Sleep Waves", "pads"},
    {"factory-407", "Fog Bank", "pads"},
    {"factory-408", "Stochastic", "fx"},
    {"factory-409", "Formant Speech", "fx"},
    {"factory-410", "Bowed Metal", "fx"},
    {"factory-411", "Circuit Bent", "fx"},
    {"factory-412", "Shepard Tone", "fx"},
    {"factory-413", "Data Stream", "arps"},
    {"factory-414", "Resonant Body", "fx"},
    {"factory-415", "Chaos Engine", "fx"},
    {"factory-416", "Spectral Scan", "pads"},
    {"factory-417", "Modular Glitch", "fx"},
    {"factory-418", "Cassette Warmth", "synthwave"},
    {"factory-419", "Arcade High Score", "leads"},
    {"factory-420", "VHS Sunset", "pads"},
    {"factory-421", "Palm Trees", "synthwave"},
    {"factory-422", "Grid Runner", "synthwave"},
    {"factory-423", "Tron Lightcycle", "leads"},
    {"factory-424", "Laserdisc", "synthwave"},
    {"factory-425", "Mallsoft Pad", "pads"},
    {"factory-426", "Outrun Drift", "synthwave"},
    {"factory-427", "CRT Glow", "synthwave"},
    {"factory-428", "Felt Piano", "keys"},
    {"factory-430", "Clavichord", "keys"},
    {"factory-432", "Crumhorn", "keys"},
    {"factory-433", "Dulcimer", "keys"},
    {"factory-434", "Rhodes MKI", "keys"},
    {"factory-435", "Wurlitzer 200", "keys"},
    {"factory-439", "Moog Sub", "bass"},
    {"factory-440", "FM Sub", "bass"},
    {"factory-442", "Upright Bass", "bass"},
    {"factory-443", "Distorted 808", "bass"},
    {"factory-444", "Garage Bass", "bass"},
    {"factory-445", "Techno Kick", "bass"},
    {"factory-446", "Sidechain Bass", "bass"},
    {"factory-447", "Dub Bass", "bass"},
    {"factory-448", "Soprano Sax", "leads"},
    {"factory-449", "Shakuhachi", "leads"},
    {"factory-450", "Oboe", "leads"},
    {"factory-451", "Pan Flute", "leads"},
    {"factory-452", "Theremin", "leads"},
    {"factory-453", "Glass Harmonica", "leads"},
    {"factory-454", "Trumpet", "leads"},
    {"factory-455", "Violin", "leads"},
    {"factory-457", "Didgeridoo", "leads"},
    {"factory-458", "Sequenced Pluck", "arps"},
    {"factory-459", "Gated Pluck", "arps"},
    {"factory-460", "Harpsichord Arp", "arps"},
    {"factory-461", "Synth Harp", "arps"},
    {"factory-463", "Koto Pluck", "arps"},
    {"factory-464", "Banjo Twang", "arps"},
    {"factory-465", "Sitar Drone", "arps"},
    {"factory-466", "Pizzicato", "arps"},
    {"factory-467", "Hammered", "arps"},
    {"factory-468", "Taiko Drum", "fx"},
    {"factory-469", "Steel Tongue", "fx"},
    {"factory-470", "Singing Bowl", "fx"},
    {"factory-472", "Wood Block", "fx"},
    {"factory-473", "Anvil", "fx"},
    {"factory-474", "Thunder", "fx"},
    {"factory-475", "Tuning Fork", "fx"},
    {"factory-477", "Reverse Cymbal", "fx"},
    {"factory-478", "Atmosphere 15", "pads"},
    {"factory-479", "Ethereal 55", "pads"},
    {"factory-480", "Dream Pad 30", "pads"},
    {"factory-481", "Spirit Pad 8", "pads"},
    {"factory-482", "Space Pad 18", "pads"},
    {"factory-483", "Drone Pad 56", "pads"},
    {"factory-484", "Drone Pad 31", "pads"},
    {"factory-485", "Dream Pad 84", "pads"},
    {"factory-486", "Mystic Pad 74", "pads"},
    {"factory-487", "Dark Pad 24", "pads"},
    {"factory-488", "Warm Pad 50", "pads"},
    {"factory-489", "Crystal Pad 9", "pads"},
    {"factory-490", "Spirit Pad 10", "pads"},
    {"factory-491", "Glass Pad 34", "pads"},
    {"factory-492", "Mystic Pad 57", "pads"},
    {"factory-493", "Pulsing Pad 72", "pads"},
    {"factory-494", "Cloud Pad 59", "pads"},
    {"factory-495", "String Pad 14", "pads"},
    {"factory-496", "Texture Pad 41", "pads"},
    {"factory-497", "Mellow Pad 57", "pads"},
    {"factory-498", "Atmosphere 74", "pads"},
    {"factory-499", "Heaven Pad 58", "pads"},
    {"factory-500", "Dark Pad 53", "pads"},
    {"factory-501", "Ambient Pad 56", "pads"},
    {"factory-502", "Spirit Pad 49", "pads"},
    {"factory-503", "Bell Pad 28", "pads"},
    {"factory-504", "Bell Pad 6", "pads"},
    {"factory-505", "Mystic Pad 76", "pads"},
    {"factory-506", "Analog Pad 31", "pads"},
    {"factory-507", "Ambient Pad 30", "pads"},
    {"factory-508", "Scream Lead 97", "leads"},
    {"factory-509", "Reso Lead 16", "leads"},
    {"factory-510", "Reso Lead 23", "leads"},
    {"factory-511", "Scream Lead 20", "leads"},
    {"factory-512", "Saw Lead 12", "leads"},
    {"factory-513", "Soft Lead 14", "leads"},
    {"factory-514", "Digital Lead 47", "leads"},
    {"factory-515", "Detuned Lead 60", "leads"},
    {"factory-516", "Digital Lead 35", "leads"},
    {"factory-517", "808 Lead 61", "leads"},
    {"factory-518", "Pluck Lead 44", "leads"},
    {"factory-519", "Synth Lead 22", "leads"},
    {"factory-520", "Synth Lead 82", "leads"},
    {"factory-521", "Guitar Lead 74", "leads"},
    {"factory-522", "Reso Lead 82", "leads"},
    {"factory-523", "Super Saw 33", "leads"},
    {"factory-524", "Flute Lead 87", "leads"},
    {"factory-525", "Square Lead 39", "leads"},
    {"factory-526", "Fuzz Lead 48", "leads"},
    {"factory-527", "Brass Lead 32", "leads"},
    {"factory-528", "Saw Lead 46", "leads"},
    {"factory-529", "Scream Lead 4", "leads"},
    {"factory-530", "Digital Lead 78", "leads"},
    {"factory-531", "Pulse Lead 56", "leads"},
    {"factory-532", "Unison Lead 85", "leads"},
    {"factory-533", "Pluck Lead 90", "leads"},
    {"factory-534", "Unison Lead 21", "leads"},
    {"factory-535", "Acid Lead 39", "leads"},
    {"factory-536", "Pulse Lead 41", "leads"},
    {"factory-537", "Bell Lead 96", "leads"},
    {"factory-538", "Techno Bass 81", "bass"},
    {"factory-539", "Analog Bass 58", "bass"},
    {"factory-540", "Sub Drop 61", "bass"},
    {"factory-541", "House Bass 81", "bass"},
    {"factory-542", "Sine Bass 49", "bass"},
    {"factory-543", "Square Bass 99", "bass"},
    {"factory-544", "Techno Bass 96", "bass"},
    {"factory-545", "Slap Bass 48", "bass"},
    {"factory-546", "Square Bass 48", "bass"},
    {"factory-547", "Sub Bass 33", "bass"},
    {"factory-548", "Neuro Bass 19", "bass"},
    {"factory-549", "Dark Bass 33", "bass"},
    {"factory-550", "Acid Bass 92", "bass"},
    {"factory-551", "Rubber Bass 16", "bass"},
    {"factory-552", "Deep Bass 14", "bass"},
    {"factory-553", "Dark Bass 66", "bass"},
    {"factory-554", "Bright Bass 41", "bass"},
    {"factory-555", "Growl Bass 92", "bass"},
    {"factory-556", "Squelch Bass 64", "bass"},
    {"factory-557", "Analog Bass 60", "bass"},
    {"factory-558", "Slap Bass 11", "bass"},
    {"factory-559", "Funk Bass 4", "bass"},
    {"factory-560", "Acid Bass 89", "bass"},
    {"factory-561", "Rubber Bass 58", "bass"},
    {"factory-562", "Bright Bass 65", "bass"},
    {"factory-563", "Dark Bass 71", "bass"},
    {"factory-564", "Reese Bass 5", "bass"},
    {"factory-565", "Saw Bass 3", "bass"},
    {"factory-566", "Wobble Bass 88", "bass"},
    {"factory-567", "Sine Bass 42", "bass"},
    {"factory-568", "Synth Keys 91", "keys"},
    {"factory-569", "Pluck Keys 38", "keys"},
    {"factory-570", "Jazz Keys 7", "keys"},
    {"factory-571", "Warm Keys 62", "keys"},
    {"factory-572", "Soft Keys 5", "keys"},
    {"factory-573", "Funky Keys 60", "keys"},
    {"factory-574", "Crystal Keys 66", "keys"},
    {"factory-575", "Harpsichord Keys 89", "keys"},
    {"factory-576", "Metallic Keys 96", "keys"},
    {"factory-577", "Space Keys 15", "keys"},
    {"factory-578", "Pluck Keys 66", "keys"},
    {"factory-579", "FM Keys 61", "keys"},
    {"factory-580", "Disco Keys 18", "keys"},
    {"factory-581", "Metallic Keys 45", "keys"},
    {"factory-582", "Digital Keys 32", "keys"},
    {"factory-583", "Synth Keys 19", "keys"},
    {"factory-584", "Clav Keys 90", "keys"},
    {"factory-585", "Glass Keys 32", "keys"},
    {"factory-586", "Disco Keys 28", "keys"},
    {"factory-587", "Disco Keys 42", "keys"},
    {"factory-588", "Jazz Keys 95", "keys"},
    {"factory-589", "Warm Keys 59", "keys"},
    {"factory-590", "Pluck Keys 81", "keys"},
    {"factory-591", "Pop Keys 69", "keys"},
    {"factory-592", "Glass Keys 59", "keys"},
    {"factory-593", "FM Keys 64", "keys"},
    {"factory-594", "Space Keys 85", "keys"},
    {"factory-595", "Disco Keys 43", "keys"},
    {"factory-596", "Pop Keys 58", "keys"},
    {"factory-597", "Pluck Keys 95", "keys"},
    {"factory-598", "Down Arp 77", "arps"},
    {"factory-599", "House Arp 39", "arps"},
    {"factory-600", "Bell Arp 78", "arps"},
    {"factory-601", "Trance Arp 91", "arps"},
    {"factory-602", "Breakbeat Arp 5", "arps"},
    {"factory-603", "Pad Arp 29", "arps"},
    {"factory-604", "UpDown Arp 57", "arps"},
    {"factory-605", "Pattern Arp 82", "arps"},
    {"factory-606", "Pad Arp 86", "arps"},
    {"factory-607", "UpDown Arp 24", "arps"},
    {"factory-608", "Synth Arp 2", "arps"},
    {"factory-609", "Breakbeat Arp 66", "arps"},
    {"factory-610", "Trance Arp 16", "arps"},
    {"factory-611", "Glitch Arp 35", "arps"},
    {"factory-612", "Acid Arp 58", "arps"},
    {"factory-613", "Breakbeat Arp 51", "arps"},
    {"factory-614", "Pattern Arp 57", "arps"},
    {"factory-615", "House Arp 84", "arps"},
    {"factory-616", "Bell Arp 48", "arps"},
    {"factory-617", "UpDown Arp 18", "arps"},
    {"factory-618", "Acid Arp 38", "arps"},
    {"factory-619", "Down Arp 3", "arps"},
    {"factory-620", "Breakbeat Arp 42", "arps"},
    {"factory-621", "Pattern Arp 64", "arps"},
    {"factory-622", "Trance Arp 66", "arps"},
    {"factory-623", "Up Arp 71", "arps"},
    {"factory-624", "Down Arp 71", "arps"},
    {"factory-625", "Classic Arp 43", "arps"},
    {"factory-626", "Down Arp 75", "arps"},
    {"factory-627", "Bass Arp 18", "arps"},
    {"factory-628", "Crash 19", "fx"},
    {"factory-629", "Impact 43", "fx"},
    {"factory-630", "Vocoder 70", "fx"},
    {"factory-631", "Alarm 76", "fx"},
    {"factory-632", "Arcade 13", "fx"},
    {"factory-633", "Impact 91", "fx"},
    {"factory-634", "Siren 22", "fx"},
    {"factory-635", "Impact 38", "fx"},
    {"factory-636", "Modem 67", "fx"},
    {"factory-637", "Pixel 51", "fx"},
    {"factory-638", "Siren 89", "fx"},
    {"factory-639", "Formant 52", "fx"},
    {"factory-640", "Rise 21", "fx"},
    {"factory-641", "Arcade 14", "fx"},
    {"factory-642", "Sweep 75", "fx"},
    {"factory-643", "Robot 16", "fx"},
    {"factory-644", "Thunder 98", "fx"},
    {"factory-645", "Robot 94", "fx"},
    {"factory-646", "UFO 49", "fx"},
    {"factory-647", "Laser 2", "fx"},
    {"factory-648", "UFO 80", "fx"},
    {"factory-649", "Stab 53", "fx"},
    {"factory-650", "Glitch 43", "fx"},
    {"factory-651", "Siren 72", "fx"},
    {"factory-652", "Arcade 16", "fx"},
    {"factory-653", "Noise Burst 18", "fx"},
    {"factory-654", "Modem 19", "fx"},
    {"factory-655", "Explosion 82", "fx"},
    {"factory-656", "Wind 67", "fx"},
    {"factory-657", "Formant 66", "fx"},
    {"factory-658", "Grid Runner 30", "synthwave"},
    {"factory-659", "Palm Trees 98", "synthwave"},
    {"factory-660", "VHS Keys 6", "synthwave"},
    {"factory-661", "Palm Trees 86", "synthwave"},
    {"factory-662", "Outrun Lead 1", "synthwave"},
    {"factory-663", "Tangerine Pad 81", "synthwave"},
    {"factory-664", "Coastal Drive 66", "synthwave"},
    {"factory-665", "Kraftwerk Keys 63", "synthwave"},
    {"factory-666", "Blade Runner 49", "synthwave"},
    {"factory-667", "Cassette Pad 24", "synthwave"},
    {"factory-668", "Grid Runner 19", "synthwave"},
    {"factory-669", "Tron Bass 85", "synthwave"},
    {"factory-670", "Cyber Bass 62", "synthwave"},
    {"factory-671", "Miami Nights 62", "synthwave"},
    {"factory-672", "Grid Runner 47", "synthwave"},
    {"factory-673", "Carpenter Lead 21", "synthwave"},
    {"factory-674", "Tron Bass 5", "synthwave"},
    {"factory-675", "Laser Disc 31", "synthwave"},
    {"factory-676", "Tron Bass 25", "synthwave"},
    {"factory-677", "Kraftwerk Keys 44", "synthwave"},
    {"factory-678", "Vaporwave Keys 87", "synthwave"},
    {"factory-679", "Cassette Pad 14", "synthwave"},
    {"factory-680", "Kraftwerk Keys 74", "synthwave"},
    {"factory-681", "Tron Bass 34", "synthwave"},
    {"factory-682", "Dream Pad 72", "synthwave"},
    {"factory-683", "Upright Piano 28", "piano"},
    {"factory-684", "Classical Piano 23", "piano"},
    {"factory-685", "Bright Piano 11", "piano"},
    {"factory-686", "Concert Grand 85", "piano"},
    {"factory-687", "Dark Piano 40", "piano"},
    {"factory-689", "Honky Tonk 45", "piano"},
    {"factory-690", "Dark Piano 49", "piano"},
    {"factory-691", "Ballad Piano 90", "piano"},
    {"factory-692", "Rock Piano 48", "piano"},
    {"factory-693", "Concert Grand 50", "piano"},
    {"factory-694", "Soft Piano 33", "piano"},
    {"factory-695", "Rock Piano 89", "piano"},
    {"factory-696", "Classical Piano 83", "piano"},
    {"factory-697", "Pop Piano 36", "piano"},
    {"factory-698", "Studio Piano 93", "piano"},
    {"factory-699", "Stage Piano 14", "piano"},
    {"factory-700", "Bright Piano 60", "piano"},
    {"factory-701", "Classical Piano 50", "piano"},
    {"factory-702", "Jazz Piano 44", "piano"},
    {"factory-703", "Ballad Piano 47", "piano"},
    {"factory-704", "Ballad Piano 71", "piano"},
    {"factory-705", "Studio Piano 62", "piano"},
    {"factory-706", "Soft Piano 99", "piano"},
    {"factory-707", "Pop Piano 97", "piano"},
    {"factory-708", "Hammond Growl 72", "organ"},
    {"factory-709", "Theater Organ 77", "organ"},
    {"factory-710", "Jazz Organ 80", "organ"},
    {"factory-711", "Hammond B3 49", "organ"},
    {"factory-712", "Baroque Organ 30", "organ"},
    {"factory-713", "Church Organ 3", "organ"},
    {"factory-714", "Baroque Organ 85", "organ"},
    {"factory-715", "Rotary Organ 70", "organ"},
    {"factory-716", "Church Organ 41", "organ"},
    {"factory-717", "Electric Organ 73", "organ"},
    {"factory-718", "Hammond C3 53", "organ"},
    {"factory-719", "Hammond C3 78", "organ"},
    {"factory-720", "Hammond C3 72", "organ"},
    {"factory-721", "Farfisa 93", "organ"},
    {"factory-722", "Farfisa 15", "organ"},
    {"factory-723", "Cathedral Organ 23", "organ"},
    {"factory-724", "Electric Organ 64", "organ"},
    {"factory-725", "Cathedral Organ 5", "organ"},
    {"factory-726", "Farfisa 99", "organ"},
    {"factory-727", "Rotary Organ 94", "organ"},
    {"factory-728", "Gospel Organ 25", "organ"},
    {"factory-729", "Farfisa 40", "organ"},
    {"factory-730", "Cathedral Organ 62", "organ"},
    {"factory-731", "Farfisa 20", "organ"},
    {"factory-732", "Hammond Growl 31", "organ"},
    {"factory-733", "Finger Pick 68", "guitar"},
    {"factory-734", "Fingerstyle 77", "guitar"},
    {"factory-735", "Baroque Guitar 57", "guitar"},
    {"factory-736", "Classical Guitar 10", "guitar"},
    {"factory-737", "Romantic Guitar 89", "guitar"},
    {"factory-738", "Steel String 59", "guitar"},
    {"factory-739", "Clean Strat 59", "guitar"},
    {"factory-740", "Steel String 39", "guitar"},
    {"factory-741", "Clean Strat 70", "guitar"},
    {"factory-742", "Archtop 14", "guitar"},
    {"factory-743", "Classical Guitar 58", "guitar"},
    {"factory-744", "Archtop 2", "guitar"},
    {"factory-745", "Flamenco 56", "guitar"},
    {"factory-746", "Jazz Guitar 86", "guitar"},
    {"factory-747", "Parlor Guitar 55", "guitar"},
    {"factory-748", "Semi Hollow 74", "guitar"},
    {"factory-749", "Semi Hollow 11", "guitar"},
    {"factory-750", "Les Paul 59", "guitar"},
    {"factory-751", "Classical Guitar 74", "guitar"},
    {"factory-752", "Finger Pick 15", "guitar"},
    {"factory-753", "Classical Guitar 77", "guitar"},
    {"factory-754", "Steel String 7", "guitar"},
    {"factory-755", "Telecaster 87", "guitar"},
    {"factory-756", "Fingerstyle 75", "guitar"},
    {"factory-757", "Telecaster 13", "guitar"},
    {"factory-758", "Double Bass 12", "strings"},
    {"factory-759", "Cello 36", "strings"},
    {"factory-760", "Bright Strings 92", "strings"},
    {"factory-761", "Warm Strings 62", "strings"},
    {"factory-762", "Chamber Strings 11", "strings"},
    {"factory-763", "Pad Strings 31", "strings"},
    {"factory-764", "Epic Strings 20", "strings"},
    {"factory-765", "Double Bass 15", "strings"},
    {"factory-766", "Double Bass 36", "strings"},
    {"factory-767", "Pad Strings 37", "strings"},
    {"factory-768", "Soft Strings 1", "strings"},
    {"factory-769", "Pizzicato 86", "strings"},
    {"factory-770", "Pad Strings 42", "strings"},
    {"factory-771", "Pizzicato 50", "strings"},
    {"factory-772", "Bowed Strings 22", "strings"},
    {"factory-773", "String Ensemble 74", "strings"},
    {"factory-774", "Cello 3", "strings"},
    {"factory-775", "Viola 38", "strings"},
    {"factory-776", "Epic Strings 91", "strings"},
    {"factory-777", "Viola 9", "strings"},
    {"factory-778", "Cello 51", "strings"},
    {"factory-779", "Violin 38", "strings"},
    {"factory-780", "Marcato 62", "strings"},
    {"factory-781", "Chamber Strings 74", "strings"},
    {"factory-782", "Violin 95", "strings"},
    {"factory-783", "Horn Section 15", "brass"},
    {"factory-784", "French Horn 66", "brass"},
    {"factory-785", "Jazz Brass 94", "brass"},
    {"factory-786", "Muted Trumpet 9", "brass"},
    {"factory-787", "Orchestral Brass 39", "brass"},
    {"factory-788", "Synth Brass 4", "brass"},
    {"factory-789", "Soft Brass 21", "brass"},
    {"factory-790", "Big Band Brass 98", "brass"},
    {"factory-791", "Bright Brass 48", "brass"},
    {"factory-792", "Tuba 54", "brass"},
    {"factory-793", "Tuba 29", "brass"},
    {"factory-794", "Brass Swell 76", "brass"},
    {"factory-795", "Soft Brass 75", "brass"},
    {"factory-796", "Jazz Brass 65", "brass"},
    {"factory-797", "Brass Stab 98", "brass"},
    {"factory-798", "Jazz Brass 9", "brass"},
    {"factory-799", "Big Band Brass 9", "brass"},
    {"factory-800", "Cinematic Brass 52", "brass"},
    {"factory-801", "Cinematic Brass 87", "brass"},
    {"factory-802", "Horn Section 3", "brass"},
    {"factory-803", "Bright Brass 92", "brass"},
    {"factory-804", "Bright Brass 42", "brass"},
    {"factory-805", "Synth Brass 83", "brass"},
    {"factory-806", "Orchestral Brass 3", "brass"},
    {"factory-807", "French Horn 69", "brass"},
    {"factory-808", "Gregorian 84", "choir"},
    {"factory-809", "Alto 82", "choir"},
    {"factory-810", "Ethereal Choir 35", "choir"},
    {"factory-811", "Mixed Choir 34", "choir"},
    {"factory-812", "Choir Pad 93", "choir"},
    {"factory-813", "Mmm Choir 19", "choir"},
    {"factory-814", "Baritone 40", "choir"},
    {"factory-815", "Choir Pad 2", "choir"},
    {"factory-816", "Dark Choir 95", "choir"},
    {"factory-817", "Ooh Choir 1", "choir"},
    {"factory-818", "Eeh Choir 88", "choir"},
    {"factory-819", "Mmm Choir 34", "choir"},
    {"factory-820", "Mmm Choir 35", "choir"},
    {"factory-821", "Chamber Choir 88", "choir"},
    {"factory-822", "Opera 86", "choir"},
    {"factory-823", "Gregorian 41", "choir"},
    {"factory-824", "Eeh Choir 41", "choir"},
    {"factory-825", "Angelic Choir 46", "choir"},
    {"factory-826", "Mystic Choir 99", "choir"},
    {"factory-827", "Angelic Choir 81", "choir"},
    {"factory-828", "Gregorian 71", "choir"},
    {"factory-829", "Opera 17", "choir"},
    {"factory-830", "Soprano 83", "choir"},
    {"factory-831", "Sacred Choir 10", "choir"},
    {"factory-832", "Ethereal Choir 91", "choir"},
    {"factory-833", "Vibraphone 2", "percussion"},
    {"factory-834", "Agogo 25", "percussion"},
    {"factory-835", "Claves 61", "percussion"},
    {"factory-836", "Claves 66", "percussion"},
    {"factory-837", "Steel Drum 61", "percussion"},
    {"factory-838", "Steel Drum 37", "percussion"},
    {"factory-839", "Castanets 5", "percussion"},
    {"factory-840", "Agogo 7", "percussion"},
    {"factory-841", "Vibraphone 20", "percussion"},
    {"factory-842", "Sleigh Bells 32", "percussion"},
    {"factory-843", "Marimba 44", "percussion"},
    {"factory-844", "Sleigh Bells 90", "percussion"},
    {"factory-845", "Concert Bass Drum 11", "percussion"},
    {"factory-846", "Timbales 55", "percussion"},
    {"factory-847", "Wind Chimes 86", "percussion"},
    {"factory-848", "Triangle 17", "percussion"},
    {"factory-849", "Agogo 59", "percussion"},
    {"factory-850", "Field Drum 39", "percussion"},
    {"factory-851", "Gong 58", "percussion"},
    {"factory-852", "Snare Drum 70", "percussion"},
    {"factory-853", "Castanets 25", "percussion"},
    {"factory-854", "Timpani 44", "percussion"},
    {"factory-855", "Snare Drum 24", "percussion"},
    {"factory-856", "Vibraphone 35", "percussion"},
    {"factory-857", "Wood Block 11", "percussion"},
    {"factory-858", "Grain 88", "custom"},
    {"factory-859", "Grain 1", "custom"},
    {"factory-860", "Mood 36", "custom"},
    {"factory-861", "Feel 36", "custom"},
    {"factory-862", "Draft 61", "custom"},
    {"factory-863", "Grain 2", "custom"},
    {"factory-864", "Test Patch 40", "custom"},
    {"factory-865", "Color 1", "custom"},
    {"factory-866", "Sketch 3", "custom"},
    {"factory-867", "Blank Canvas 17", "custom"},
    {"factory-868", "Mood 71", "custom"},
    {"factory-869", "Sketch 96", "custom"},
    {"factory-870", "Feel 57", "custom"},
    {"factory-871", "Color 43", "custom"},
    {"factory-872", "Concept 91", "custom"},
    {"factory-873", "Tone 85", "custom"},
    {"factory-874", "User Init 15", "custom"},
    {"factory-875", "Blank Canvas 1", "custom"},
    {"factory-876", "Mood 23", "custom"},
    {"factory-877", "User Init 75", "custom"},
    {"factory-878", "Rock Kit 27", "drums"},
    {"factory-879", "Jazz Kit 17", "drums"},
    {"factory-880", "Metal Kit 62", "drums"},
    {"factory-881", "Room Kit 69", "drums"},
    {"factory-882", "DnB Kit 52", "drums"},
    {"factory-883", "Breakbeat 91", "drums"},
    {"factory-884", "Tribal Kit 19", "drums"},
    {"factory-885", "House Kit 33", "drums"},
    {"factory-886", "Cyber Kit 51", "drums"},
    {"factory-887", "Techno Kit 73", "drums"},
    {"factory-888", "Vintage Kit 31", "drums"},
    {"factory-889", "DnB Kit 61", "drums"},
    {"factory-890", "Cyber Kit 18", "drums"},
    {"factory-891", "808 Kit 82", "drums"},
    {"factory-892", "Cyber Kit 50", "drums"},
    {"factory-893", "Linn Drum 62", "drums"},
    {"factory-894", "Tribal Kit 16", "drums"},
    {"factory-895", "Garage Kit 83", "drums"},
    {"factory-896", "Vintage Kit 95", "drums"},
    {"factory-897", "Drum Machine 19", "drums"},
    {"factory-898", "Garage Kit 28", "drums"},
    {"factory-899", "Trap Kit 85", "drums"},
    {"factory-900", "Drum Machine 97", "drums"},
    {"factory-902", "Linn Drum 31", "drums"},
    {"factory-903", "Linn Drum 15", "drums"},
    {"factory-904", "Linn Drum 42", "drums"},
    {"factory-905", "Jazz Kit 85", "drums"},
    {"factory-906", "Analog Kit 70", "drums"},
    {"factory-907", "Electronic Kit 13", "drums"},
    {"factory-908", "Singer Songwriter 21", "acousticGuitar"},
    {"factory-909", "Singer Songwriter 66", "acousticGuitar"},
    {"factory-910", "Dreadnought 47", "acousticGuitar"},
    {"factory-911", "12 String 76", "acousticGuitar"},
    {"factory-912", "Singer Songwriter 69", "acousticGuitar"},
    {"factory-913", "Fingerstyle Steel 91", "acousticGuitar"},
    {"factory-914", "12 String 82", "acousticGuitar"},
    {"factory-915", "Slide Acoustic 2", "acousticGuitar"},
    {"factory-916", "Acoustic Steel 92", "acousticGuitar"},
    {"factory-917", "Slide Acoustic 68", "acousticGuitar"},
    {"factory-918", "Slide Acoustic 16", "acousticGuitar"},
    {"factory-919", "Coffeehouse 63", "acousticGuitar"},
    {"factory-920", "Jumbo Acoustic 53", "acousticGuitar"},
    {"factory-921", "Folk Guitar 21", "acousticGuitar"},
    {"factory-922", "Folk Guitar 86", "acousticGuitar"},
    {"factory-923", "Dreadnought 14", "acousticGuitar"},
    {"factory-924", "Slide Acoustic 55", "acousticGuitar"},
    {"factory-925", "Open Tuning 65", "acousticGuitar"},
    {"factory-926", "Acoustic Steel 49", "acousticGuitar"},
    {"factory-927", "Grand Auditorium 41", "acousticGuitar"},
    {"factory-928", "Dreadnought 86", "acousticGuitar"},
    {"factory-929", "Dreadnought 17", "acousticGuitar"},
    {"factory-930", "Slide Acoustic 26", "acousticGuitar"},
    {"factory-931", "Travis Picking 9", "acousticGuitar"},
    {"factory-932", "Travis Picking 64", "acousticGuitar"},
    {"factory-933", "Clean Strat 66", "electricGuitar"},
    {"factory-934", "Shred Lead 32", "electricGuitar"},
    {"factory-935", "Single Coil 94", "electricGuitar"},
    {"factory-936", "Les Paul Clean 58", "electricGuitar"},
    {"factory-937", "Fusion Lead 78", "electricGuitar"},
    {"factory-938", "Les Paul Clean 32", "electricGuitar"},
    {"factory-939", "Tweed Clean 20", "electricGuitar"},
    {"factory-940", "Fusion Lead 50", "electricGuitar"},
    {"factory-941", "Blues Drive 68", "electricGuitar"},
    {"factory-942", "Math Rock 20", "electricGuitar"},
    {"factory-943", "Blues Drive 62", "electricGuitar"},
    {"factory-944", "80s Clean 12", "electricGuitar"},
    {"factory-945", "Single Coil 27", "electricGuitar"},
    {"factory-946", "Clean Strat 73", "electricGuitar"},
    {"factory-947", "Blackface 21", "electricGuitar"},
    {"factory-948", "Single Coil 51", "electricGuitar"},
    {"factory-949", "Clean Strat 31", "electricGuitar"},
    {"factory-950", "Gretsch Clean 12", "electricGuitar"},
    {"factory-951", "Clean Strat 76", "electricGuitar"},
    {"factory-952", "Blues Breaker 17", "electricGuitar"},
    {"factory-953", "British Crunch 12", "electricGuitar"},
    {"factory-954", "Modern High Gain 63", "electricGuitar"},
    {"factory-955", "Djent 83", "electricGuitar"},
    {"factory-956", "Tele Twang 11", "electricGuitar"},
    {"factory-957", "Shred Lead 28", "electricGuitar"},
    {"factory-958", "P90 52", "electricGuitar"},
    {"factory-959", "80s Clean 56", "electricGuitar"},
    {"factory-960", "Blues Breaker 19", "electricGuitar"},
    {"factory-961", "Djent 49", "electricGuitar"},
    {"factory-962", "Tele Twang 23", "electricGuitar"},
    {"factory-963", "Doom Bass 3", "bassGuitar"},
    {"factory-964", "Fretless 83", "bassGuitar"},
    {"factory-965", "Pop Bass 22", "bassGuitar"},
    {"factory-966", "Acid Bass 17", "bassGuitar"},
    {"factory-967", "Precision Bass 96", "bassGuitar"},
    {"factory-968", "Doom Bass 75", "bassGuitar"},
    {"factory-969", "Acoustic Bass 88", "bassGuitar"},
    {"factory-970", "Gibson Bass 67", "bassGuitar"},
    {"factory-971", "Fender Bass 45", "bassGuitar"},
    {"factory-972", "Sub Octave Bass 63", "bassGuitar"},
    {"factory-973", "Metal Bass 83", "bassGuitar"},
    {"factory-974", "Upright Bass 72", "bassGuitar"},
    {"factory-975", "Fretless 16", "bassGuitar"},
    {"factory-976", "Pop Bass 83", "bassGuitar"},
    {"factory-977", "Finger Bass 80", "bassGuitar"},
    {"factory-978", "Rickenbacker 7", "bassGuitar"},
    {"factory-979", "Funk Bass 62", "bassGuitar"},
    {"factory-980", "Precision Bass 86", "bassGuitar"},
    {"factory-981", "Pick Bass 25", "bassGuitar"},
    {"factory-982", "Rickenbacker 71", "bassGuitar"},
    {"factory-983", "Motown Bass 56", "bassGuitar"},
    {"factory-984", "Synth Bass Guitar 27", "bassGuitar"},
    {"factory-985", "Pop Bass 59", "bassGuitar"},
    {"factory-986", "Precision Bass 73", "bassGuitar"},
    {"factory-987", "Slap Bass 91", "bassGuitar"},
    {"factory-988", "Rhodes Stage 25", "electricPiano"},
    {"factory-989", "Dyno My Piano 73", "electricPiano"},
    {"factory-990", "Wurlitzer 7", "electricPiano"},
    {"factory-991", "Yamaha DX7 EP 5", "electricPiano"},
    {"factory-992", "CP80 39", "electricPiano"},
    {"factory-993", "Rhodes MK1 99", "electricPiano"},
    {"factory-994", "FM Electric Piano 84", "electricPiano"},
    {"factory-995", "Wurlitzer 200 39", "electricPiano"},
    {"factory-996", "DX Bell 52", "electricPiano"},
    {"factory-997", "Wurlitzer 76", "electricPiano"},
    {"factory-998", "Wurlitzer 200 60", "electricPiano"},
    {"factory-999", "FM Electric Piano 98", "electricPiano"},
    {"factory-1000", "Clavinet D6 30", "electricPiano"},
    {"factory-1001", "Soft EP 78", "electricPiano"},
    {"factory-1002", "Wurlitzer 27", "electricPiano"},
    {"factory-1003", "Wurlitzer 200 9", "electricPiano"},
    {"factory-1004", "Clavinet D6 37", "electricPiano"},
    {"factory-1005", "Bright EP 97", "electricPiano"},
    {"factory-1006", "Rhodes MK2 14", "electricPiano"},
    {"factory-1007", "Wurlitzer 200 56", "electricPiano"},
    {"factory-1008", "Yamaha DX7 EP 8", "electricPiano"},
    {"factory-1009", "Soft EP 29", "electricPiano"},
    {"factory-1010", "DX Bell 95", "electricPiano"},
    {"factory-1011", "Tremolo EP 64", "electricPiano"},
    {"factory-1012", "Rhodes MK1 44", "electricPiano"},
    {"factory-1013", "Clean Clav 31", "clavinet"},
    {"factory-1014", "Clavinet C 40", "clavinet"},
    {"factory-1015", "Muted Clav 79", "clavinet"},
    {"factory-1016", "Nasty Clav 65", "clavinet"},
    {"factory-1017", "Wah Clav 14", "clavinet"},
    {"factory-1018", "Wah Clav 53", "clavinet"},
    {"factory-1019", "Bright Clav 49", "clavinet"},
    {"factory-1020", "Guitar Clav 68", "clavinet"},
    {"factory-1022", "Staccato Clav 69", "clavinet"},
    {"factory-1023", "Staccato Clav 24", "clavinet"},
    {"factory-1024", "Staccato Clav 55", "clavinet"},
    {"factory-1025", "Staccato Clav 53", "clavinet"},
    {"factory-1026", "Nasty Clav 84", "clavinet"},
    {"factory-1027", "Muted Clav 42", "clavinet"},
    {"factory-1028", "Bright Clav 22", "clavinet"},
    {"factory-1029", "Clavinet D6 63", "clavinet"},
    {"factory-1030", "Soul Clav 34", "clavinet"},
    {"factory-1031", "Clean Clav 89", "clavinet"},
    {"factory-1032", "Guitar Clav 29", "clavinet"},
    {"factory-1033", "Music Box 5", "mallets"},
    {"factory-1034", "Orchestral Bells 13", "mallets"},
    {"factory-1035", "Tongue Drum 77", "mallets"},
    {"factory-1036", "Marimba 40", "mallets"},
    {"factory-1037", "Soft Mallets 9", "mallets"},
    {"factory-1038", "Hang Drum 14", "mallets"},
    {"factory-1039", "Xylophone 65", "mallets"},
    {"factory-1040", "Hard Mallets 61", "mallets"},
    {"factory-1041", "Steel Drum 74", "mallets"},
    {"factory-1042", "Orchestral Mallets 61", "mallets"},
    {"factory-1043", "Steel Drum 42", "mallets"},
    {"factory-1044", "Music Box 81", "mallets"},
    {"factory-1045", "Kalimba 79", "mallets"},
    {"factory-1046", "Kalimba 26", "mallets"},
    {"factory-1047", "Chime 80", "mallets"},
    {"factory-1048", "Hard Mallets 78", "mallets"},
    {"factory-1049", "Tongue Drum 42", "mallets"},
    {"factory-1050", "Balafon 72", "mallets"},
    {"factory-1051", "Kalimba 49", "mallets"},
    {"factory-1052", "Tongue Drum 51", "mallets"},
    {"factory-1053", "Celesta 91", "mallets"},
    {"factory-1054", "Crystal Bells 91", "mallets"},
    {"factory-1055", "Balafon 23", "mallets"},
    {"factory-1056", "Music Box 2", "mallets"},
    {"factory-1057", "Kalimba 35", "mallets"},
    {"factory-1058", "Irish Whistle 73", "woodwinds"},
    {"factory-1059", "Ocarina 85", "woodwinds"},
    {"factory-1060", "Clarinet 24", "woodwinds"},
    {"factory-1061", "Ney 52", "woodwinds"},
    {"factory-1062", "Bansuri 90", "woodwinds"},
    {"factory-1063", "Oboe 39", "woodwinds"},
    {"factory-1064", "Shakuhachi 86", "woodwinds"},
    {"factory-1065", "Ney 95", "woodwinds"},
    {"factory-1066", "Alto Sax 50", "woodwinds"},
    {"factory-1067", "Clarinet 84", "woodwinds"},
    {"factory-1068", "Bansuri 58", "woodwinds"},
    {"factory-1069", "Bansuri 94", "woodwinds"},
    {"factory-1070", "Soprano Sax 46", "woodwinds"},
    {"factory-1071", "Tenor Sax 59", "woodwinds"},
    {"factory-1072", "Shinobue 39", "woodwinds"},
    {"factory-1073", "Bassoon 89", "woodwinds"},
    {"factory-1074", "Recorder 85", "woodwinds"},
    {"factory-1075", "Baritone Sax 61", "woodwinds"},
    {"factory-1076", "Irish Whistle 45", "woodwinds"},
    {"factory-1077", "Soprano Sax 72", "woodwinds"},
    {"factory-1078", "Baritone Sax 71", "woodwinds"},
    {"factory-1079", "Bamboo Flute 60", "woodwinds"},
    {"factory-1080", "Flute 80", "woodwinds"},
    {"factory-1081", "Duduk 50", "woodwinds"},
    {"factory-1082", "Bansuri 57", "woodwinds"},
    {"factory-1083", "Thumb Piano 10", "ethnic"},
    {"factory-1084", "Didgeridoo 92", "ethnic"},
    {"factory-1085", "Hammered Dulcimer 34", "ethnic"},
    {"factory-1086", "Pipa 19", "ethnic"},
    {"factory-1087", "Erhu 78", "ethnic"},
    {"factory-1088", "Mbira 83", "ethnic"},
    {"factory-1089", "Zither 20", "ethnic"},
    {"factory-1090", "Kalimba 86", "ethnic"},
    {"factory-1091", "Santoor 89", "ethnic"},
    {"factory-1092", "Zither 32", "ethnic"},
    {"factory-1093", "Kora 73", "ethnic"},
    {"factory-1094", "Santoor 43", "ethnic"},
    {"factory-1095", "Pan Pipe 61", "ethnic"},
    {"factory-1096", "Ocarina 61", "ethnic"},
    {"factory-1097", "Mizmar 54", "ethnic"},
    {"factory-1098", "Didgeridoo 8", "ethnic"},
    {"factory-1099", "Dulcimer 28", "ethnic"},
    {"factory-1100", "Harmonica 32", "ethnic"},
    {"factory-1101", "Erhu 20", "ethnic"},
    {"factory-1102", "Ngoni 47", "ethnic"},
    {"factory-1103", "Harmonica 7", "ethnic"},
    {"factory-1104", "Shamisen 72", "ethnic"},
    {"factory-1105", "Balafon 10", "ethnic"},
    {"factory-1106", "Ngoni 69", "ethnic"},
    {"factory-1107", "Whistle 45", "ethnic"},
    {"factory-1108", "Void Pad 99", "pads"},
    {"factory-1109", "Zero Gravity 86", "pads"},
    {"factory-1110", "Nebulous 66", "pads"},
    {"factory-1111", "Cosmos 65", "pads"},
    {"factory-1112", "Galaxy 14", "pads"},
    {"factory-1113", "Deep Space 86", "pads"},
    {"factory-1115", "Event Horizon 65", "pads"},
    {"factory-1116", "Cosmic Dust 92", "pads"},
    {"factory-1117", "Singularity 99", "pads"},
    {"factory-1118", "Void Pad 39", "pads"},
    {"factory-1119", "Nebulous 70", "pads"},
    {"factory-1120", "Aurora 6", "pads"},
    {"factory-1121", "Galaxy 58", "pads"},
    {"factory-1122", "Deep Space 39", "pads"},
    {"factory-1123", "Spectrum 16", "leads"},
    {"factory-1124", "Cyber Solo 61", "leads"},
    {"factory-1125", "Pulse Wave 31", "leads"},
    {"factory-1126", "Infrared 81", "leads"},
    {"factory-1127", "X-Ray 27", "leads"},
    {"factory-1128", "Neon Scream 8", "leads"},
    {"factory-1129", "Laser Lead 15", "leads"},
    {"factory-1130", "Infrared 22", "leads"},
    {"factory-1131", "Photon Lead 55", "leads"},
    {"factory-1132", "Square Solo 57", "leads"},
    {"factory-1133", "X-Ray 6", "leads"},
    {"factory-1134", "Infrared 13", "leads"},
    {"factory-1135", "Neon Solo 75", "leads"},
    {"factory-1136", "Gamma Ray 81", "leads"},
    {"factory-1137", "Spectrum 32", "leads"},
    {"factory-1138", "Stellar Bass 42", "bass"},
    {"factory-1139", "Cosmic Bass 84", "bass"},
    {"factory-1140", "Dark Matter 15", "bass"},
    {"factory-1141", "Antimatter 39", "bass"},
    {"factory-1142", "Pulsar 79", "bass"},
    {"factory-1143", "Black Hole 13", "bass"},
    {"factory-1144", "Event Horizon Bass 9", "bass"},
    {"factory-1145", "Nebula Bass 79", "bass"},
    {"factory-1146", "Cosmic Bass 20", "bass"},
    {"factory-1147", "Cosmic Bass 21", "bass"},
    {"factory-1148", "Nebula Bass 72", "bass"},
    {"factory-1149", "Neutron Star 17", "bass"},
    {"factory-1150", "Dark Matter 50", "bass"},
    {"factory-1151", "Wormhole 91", "bass"},
    {"factory-1152", "Neutron Star 86", "bass"},
    {"factory-1153", "Retro Keys 22", "keys"},
    {"factory-1154", "Wurly-ish 89", "keys"},
    {"factory-1155", "Bell Keys 18", "keys"},
    {"factory-1156", "Disco Keys 22", "keys"},
    {"factory-1157", "Rhodes-ish 68", "keys"},
    {"factory-1158", "Retro Keys 49", "keys"},
    {"factory-1159", "Metallic Keys 89", "keys"},
    {"factory-1160", "Glass EP 92", "keys"},
    {"factory-1161", "Glass EP 9", "keys"},
    {"factory-1162", "Digital Piano 47", "keys"},
    {"factory-1163", "Crystal EP 99", "keys"},
    {"factory-1164", "Cyber Keys 58", "keys"},
    {"factory-1165", "Retro Keys 37", "keys"},
    {"factory-1166", "Crystal EP 62", "keys"},
    {"factory-1167", "Soft EP 96", "keys"},
    {"factory-1168", "Pulsar Arp 11", "arps"},
    {"factory-1169", "Photon Arp 47", "arps"},
    {"factory-1170", "Dark Matter Arp 60", "arps"},
    {"factory-1171", "Galactic Arp 26", "arps"},
    {"factory-1172", "Dark Matter Arp 86", "arps"},
    {"factory-1173", "Neon Arp 6", "arps"},
    {"factory-1174", "Nebula Arp 84", "arps"},
    {"factory-1175", "Laser Arp 29", "arps"},
    {"factory-1176", "Dark Matter Arp 28", "arps"},
    {"factory-1177", "Photon Arp 35", "arps"},
    {"factory-1178", "Nebula Arp 42", "arps"},
    {"factory-1179", "Stellar Arp 79", "arps"},
    {"factory-1180", "Pulsar Arp 15", "arps"},
    {"factory-1181", "Cyber Arp 62", "arps"},
    {"factory-1182", "Nebula Arp 53", "arps"},
    {"factory-1183", "Interference 54", "fx"},
    {"factory-1184", "Pink Noise 61", "fx"},
    {"factory-1185", "Harmonic 79", "fx"},
    {"factory-1186", "Feedback Loop 54", "fx"},
    {"factory-1187", "Data Burst 9", "fx"},
    {"factory-1188", "Infrasound 73", "fx"},
    {"factory-1189", "Feedback Loop 68", "fx"},
    {"factory-1190", "Harmonic 53", "fx"},
    {"factory-1191", "Signal Loss 35", "fx"},
    {"factory-1192", "Oscillation 95", "fx"},
    {"factory-1193", "White Noise 57", "fx"},
    {"factory-1194", "Oscillation 56", "fx"},
    {"factory-1195", "Interference 44", "fx"},
    {"factory-1196", "Oscillation 48", "fx"},
    {"factory-1197", "Transmission 97", "fx"},
    {"factory-1198", "Matrix Drive 29", "synthwave"},
    {"factory-1199", "Simulation Drive 98", "synthwave"},
    {"factory-1200", "Present Drive 91", "synthwave"},
    {"factory-1201", "Laser Drive 31", "synthwave"},
    {"factory-1202", "Simulation Drive 70", "synthwave"},
    {"factory-1203", "Analog Drive 65", "synthwave"},
    {"factory-1204", "Future Drive 68", "synthwave"},
    {"factory-1205", "Photon Drive 20", "synthwave"},
    {"factory-1206", "Laser Drive 7", "synthwave"},
    {"factory-1208", "Past Drive 51", "synthwave"},
    {"factory-1209", "Cyber Drive 67", "synthwave"},
    {"factory-1210", "Live Room 12", "piano"},
    {"factory-1211", "Parlor 49", "piano"},
    {"factory-1212", "Salon 96", "piano"},
    {"factory-1213", "Recital Hall 71", "piano"},
    {"factory-1214", "Drawing Room 88", "piano"},
    {"factory-1215", "Practice Room 88", "piano"},
    {"factory-1216", "Drawing Room 65", "piano"},
    {"factory-1217", "Coffee Shop 40", "piano"},
    {"factory-1218", "Recital Hall 43", "piano"},
    {"factory-1219", "Coffee Shop 59", "piano"},
    {"factory-1220", "Coffee Shop 90", "piano"},
    {"factory-1221", "Recording Booth 15", "piano"},
    {"factory-1222", "Pagoda 77", "organ"},
    {"factory-1223", "Pagoda 45", "organ"},
    {"factory-1224", "Synagogue 77", "organ"},
    {"factory-1225", "Chapel 62", "organ"},
    {"factory-1226", "Synagogue 70", "organ"},
    {"factory-1227", "Gurdwara 18", "organ"},
    {"factory-1228", "Chapel 12", "organ"},
    {"factory-1229", "Abbey 33", "organ"},
    {"factory-1230", "Stupa 70", "organ"},
    {"factory-1231", "Chapel 24", "organ"},
    {"factory-1232", "Synagogue 51", "organ"},
    {"factory-1233", "Monastery 76", "organ"},
    {"factory-1234", "Bachata Guitar 27", "guitar"},
    {"factory-1235", "Tango Guitar 94", "guitar"},
    {"factory-1236", "Samba Guitar 49", "guitar"},
    {"factory-1237", "Reggae Guitar 37", "guitar"},
    {"factory-1238", "Bachata Guitar 86", "guitar"},
    {"factory-1239", "Bossa Guitar 91", "guitar"},
    {"factory-1240", "Flamenco Guitar 43", "guitar"},
    {"factory-1241", "Flamenco Guitar 65", "guitar"},
    {"factory-1242", "Son Guitar 84", "guitar"},
    {"factory-1243", "Salsa Guitar 27", "guitar"},
    {"factory-1244", "Bossa Guitar 58", "guitar"},
    {"factory-1245", "Ska Guitar 73", "guitar"},
    {"factory-1246", "Quartet 69", "strings"},
    {"factory-1247", "Trio 41", "strings"},
    {"factory-1248", "Octet 45", "strings"},
    {"factory-1249", "Sextet 50", "strings"},
    {"factory-1250", "Ensemble Medium 52", "strings"},
    {"factory-1251", "Duet 39", "strings"},
    {"factory-1252", "Trio 81", "strings"},
    {"factory-1253", "Quintet 15", "strings"},
    {"factory-1254", "Solo Cello 13", "strings"},
    {"factory-1255", "Solo Viola 83", "strings"},
    {"factory-1256", "Ensemble Large 40", "strings"},
    {"factory-1257", "Duet 19", "strings"},
    {"factory-1258", "Alert 58", "brass"},
    {"factory-1259", "Siren 55", "brass"},
    {"factory-1260", "Klaxon 44", "brass"},
    {"factory-1261", "Fanfare 31", "brass"},
    {"factory-1262", "Reveille 71", "brass"},
    {"factory-1263", "Reveille 23", "brass"},
    {"factory-1264", "Signal 56", "brass"},
    {"factory-1265", "Horn Blast 66", "brass"},
    {"factory-1266", "Trumpet Voluntary 82", "brass"},
    {"factory-1267", "Siren 96", "brass"},
    {"factory-1268", "Fanfare 99", "brass"},
    {"factory-1269", "Trumpet Voluntary 49", "brass"},
    {"factory-1270", "Archangel 31", "choir"},
    {"factory-1271", "Convert 38", "choir"},
    {"factory-1272", "Angel 1", "choir"},
    {"factory-1273", "Follower 3", "choir"},
    {"factory-1274", "Heavenly Host 62", "choir"},
    {"factory-1275", "Seraphim 44", "choir"},
    {"factory-1276", "Devotee 30", "choir"},
    {"factory-1277", "Seraphim 32", "choir"},
    {"factory-1278", "Prophet 9", "choir"},
    {"factory-1279", "Acolyte 80", "choir"},
    {"factory-1280", "Archangel 8", "choir"},
    {"factory-1281", "Saint 59", "choir"},
    {"factory-1282", "Just Intonation 92", "percussion"},
    {"factory-1283", "Junk Band 19", "percussion"},
    {"factory-1284", "Alternate Tuning 92", "percussion"},
    {"factory-1285", "Drumline 98", "percussion"},
    {"factory-1286", "Marching Band 25", "percussion"},
    {"factory-1287", "Drum Corps 97", "percussion"},
    {"factory-1288", "Steel Band 61", "percussion"},
    {"factory-1289", "Just Intonation 28", "percussion"},
    {"factory-1290", "Extended Technique 75", "percussion"},
    {"factory-1291", "Equal Temperament 4", "percussion"},
    {"factory-1292", "Marching Band 13", "percussion"},
    {"factory-1293", "Kitchen Band 11", "percussion"},
    {"factory-1294", "Formula 1 10", "custom"},
    {"factory-1295", "Theorem 2 4", "custom"},
    {"factory-1296", "Algorithm A 71", "custom"},
    {"factory-1297", "Equation A 26", "custom"},
    {"factory-1298", "Formula 2 78", "custom"},
    {"factory-1299", "Equation B 21", "custom"},
    {"factory-1300", "Algorithm C 42", "custom"},
    {"factory-1301", "Equation A 41", "custom"},
    {"factory-1302", "Formula 2 24", "custom"},
    {"factory-1303", "Proof A 10", "custom"},
    {"factory-1304", "Swing Beat 83", "drums"},
    {"factory-1305", "Soukous 24", "drums"},
    {"factory-1306", "Samba Beat 85", "drums"},
    {"factory-1307", "Shuffle Beat 62", "drums"},
    {"factory-1308", "Afrobeat 39", "drums"},
    {"factory-1309", "Funky Drummer 14", "drums"},
    {"factory-1310", "Mbalax 93", "drums"},
    {"factory-1311", "Swing Beat 84", "drums"},
    {"factory-1312", "Highlife 39", "drums"},
    {"factory-1313", "Think Break 8", "drums"},
    {"factory-1314", "Soukous 7", "drums"},
    {"factory-1315", "Samba Beat 72", "drums"},
    {"factory-1316", "Highlife 46", "drums"},
    {"factory-1317", "Bossa Beat 62", "drums"},
    {"factory-1318", "Soukous 15", "drums"},
    {"factory-1319", "Folk Blues 16", "acousticGuitar"},
    {"factory-1320", "Stride Piano 13", "acousticGuitar"},
    {"factory-1321", "Ragtime Guitar 13", "acousticGuitar"},
    {"factory-1322", "Stride Piano 47", "acousticGuitar"},
    {"factory-1323", "Chicago Blues 28", "acousticGuitar"},
    {"factory-1324", "Delta Blues 21", "acousticGuitar"},
    {"factory-1325", "Texas Blues 49", "acousticGuitar"},
    {"factory-1326", "New Orleans Blues 37", "acousticGuitar"},
    {"factory-1327", "Fingerstyle Blues 83", "acousticGuitar"},
    {"factory-1328", "Boogie Woogie 59", "acousticGuitar"},
    {"factory-1329", "Stride Piano 94", "acousticGuitar"},
    {"factory-1330", "Fingerstyle Blues 11", "acousticGuitar"},
    {"factory-1331", "Secundal 35", "electricGuitar"},
    {"factory-1332", "Altered Chord 31", "electricGuitar"},
    {"factory-1333", "Added Tone 80", "electricGuitar"},
    {"factory-1334", "Power Chord 89", "electricGuitar"},
    {"factory-1335", "Suspended Chord 2", "electricGuitar"},
    {"factory-1336", "Power Chord 28", "electricGuitar"},
    {"factory-1337", "Quintal 32", "electricGuitar"},
    {"factory-1338", "Mixed Interval 84", "electricGuitar"},
    {"factory-1339", "Power Chord 66", "electricGuitar"},
    {"factory-1340", "Cluster 17", "electricGuitar"},
    {"factory-1341", "Jazz Chord 7", "electricGuitar"},
    {"factory-1342", "Open Chord 70", "electricGuitar"},
    {"factory-1343", "Added Tone 95", "electricGuitar"},
    {"factory-1344", "Tone Cluster 85", "electricGuitar"},
    {"factory-1345", "Quintal 90", "electricGuitar"},
    {"factory-1346", "Chordal Bass 24", "bassGuitar"},
    {"factory-1347", "Bicycle Bass 95", "bassGuitar"},
    {"factory-1348", "Chordal Bass 39", "bassGuitar"},
    {"factory-1349", "Pedal Point 58", "bassGuitar"},
    {"factory-1350", "Obbligato Bass 85", "bassGuitar"},
    {"factory-1351", "Obbligato Bass 27", "bassGuitar"},
    {"factory-1352", "Walking Bass 69", "bassGuitar"},
    {"factory-1353", "Root Five 9", "bassGuitar"},
    {"factory-1354", "Pedal Point 24", "bassGuitar"},
    {"factory-1355", "Pedal Point 54", "bassGuitar"},
    {"factory-1356", "Chordal Bass 59", "bassGuitar"},
    {"factory-1357", "Melodic Bass 37", "bassGuitar"},
    {"factory-1358", "Fazioli 66", "electricPiano"},
    {"factory-1359", "Yamaha 27", "electricPiano"},
    {"factory-1360", "Fazioli 76", "electricPiano"},
    {"factory-1361", "Virginal 19", "electricPiano"},
    {"factory-1362", "Cristofori 77", "electricPiano"},
    {"factory-1363", "Casio 21", "electricPiano"},
    {"factory-1364", "Bluthner 44", "electricPiano"},
    {"factory-1365", "Bosendorfer 91", "electricPiano"},
    {"factory-1366", "Harpsichord 81", "electricPiano"},
    {"factory-1367", "Bluthner 7", "electricPiano"},
    {"factory-1368", "Harpsichord 88", "electricPiano"},
    {"factory-1369", "Bechstein 72", "electricPiano"},
    {"factory-1370", "Fender Rhodes 32", "clavinet"},
    {"factory-1371", "Vintage Vibe 79", "clavinet"},
    {"factory-1372", "Rhodes Stage 70", "clavinet"},
    {"factory-1373", "Rhodes Suitcase 77", "clavinet"},
    {"factory-1374", "Hohner Cembalet 33", "clavinet"},
    {"factory-1375", "Wurlitzer 140 50", "clavinet"},
    {"factory-1376", "Rhodes Suitcase 13", "clavinet"},
    {"factory-1377", "Hohner Pianet 86", "clavinet"},
    {"factory-1378", "Mark I 33", "clavinet"},
    {"factory-1379", "Rhodes Stage 29", "clavinet"},
    {"factory-1380", "Glock 18", "mallets"},
    {"factory-1381", "Thunder Tube 74", "mallets"},
    {"factory-1382", "Steel Pan 60", "mallets"},
    {"factory-1383", "Thunder Tube 51", "mallets"},
    {"factory-1384", "Tongue Drum 7", "mallets"},
    {"factory-1385", "Wind Wand 16", "mallets"},
    {"factory-1386", "Thunder Tube 18", "mallets"},
    {"factory-1387", "Marimba 17", "mallets"},
    {"factory-1388", "Steel Pan 33", "mallets"},
    {"factory-1389", "Tongue Drum 79", "mallets"},
    {"factory-1390", "Steel Pan 61", "mallets"},
    {"factory-1391", "Music Box 3", "mallets"},
    {"factory-1392", "Bass Flute 76", "woodwinds"},
    {"factory-1393", "Piccolo 31", "woodwinds"},
    {"factory-1394", "Native Flute 34", "woodwinds"},
    {"factory-1395", "Korean Flute 73", "woodwinds"},
    {"factory-1396", "Recorder 21", "woodwinds"},
    {"factory-1397", "Irish Flute 56", "woodwinds"},
    {"factory-1398", "Alto Flute 78", "woodwinds"},
    {"factory-1399", "Piccolo 64", "woodwinds"},
    {"factory-1400", "Irish Flute 33", "woodwinds"},
    {"factory-1401", "Alto Flute 96", "woodwinds"},
    {"factory-1402", "Piccolo 95", "woodwinds"},
    {"factory-1403", "Whistle 17", "woodwinds"},
    {"factory-1404", "Esraj 7", "ethnic"},
    {"factory-1405", "Kokyu 95", "ethnic"},
    {"factory-1406", "Gusle 5", "ethnic"},
    {"factory-1407", "Jews Harp 54", "ethnic"},
    {"factory-1408", "Dilruba 26", "ethnic"},
    {"factory-1409", "Mouth Harp 40", "ethnic"},
    {"factory-1410", "Gadulka 10", "ethnic"},
    {"factory-1411", "Dilruba 30", "ethnic"},
    {"factory-1412", "Rebab 31", "ethnic"},
    {"factory-1413", "Erhu 49", "ethnic"},
    {"factory-1414", "Sarangi 76", "ethnic"},
    {"factory-1415", "Haegeum 66", "ethnic"},
    {"factory-org-01", "Tonewheel Classic", "organ"},
    {"factory-ep-01", "Classic Rhodes", "electricPiano"},
    {"factory-ep-02", "Wurlitzer 200A", "electricPiano"},
    {"factory-ep-03", "DX7 Full Tines", "electricPiano"},
    {"factory-ep-04", "Stage Mark II", "electricPiano"},
    {"factory-clv-01", "Funky Clav", "clavinet"},
    {"factory-clv-02", "Superstition Clav", "clavinet"},
    {"factory-clv-03", "Muted Clav", "clavinet"},
    {"factory-ag-01", "Nylon String", "acousticGuitar"},
    {"factory-ag-02", "Steel String", "acousticGuitar"},
    {"factory-ag-03", "Fingerstyle", "acousticGuitar"},
    {"factory-eg-01", "Clean Strat", "electricGuitar"},
    {"factory-eg-02", "Crunch Lead", "electricGuitar"},
    {"factory-eg-03", "Ambient Swell", "electricGuitar"},
    {"factory-bg-01", "Finger Bass", "bassGuitar"},
    {"factory-bg-03", "Fretless Mwah", "bassGuitar"},
    {"factory-str-01", "Chamber Strings", "strings"},
    {"factory-str-03", "Solo Violin", "strings"},
    {"factory-brs-01", "Trumpet Section", "brass"},
    {"factory-brs-03", "Saxophone Alto", "brass"},
    {"factory-ww-01", "Concert Flute", "woodwinds"},
    {"factory-ww-02", "Clarinet", "woodwinds"},
    {"factory-eth-04", "Erhu", "ethnic"},
};

} // namespace opensynth